### ISSUE TITLE
I though competition between mod maker was prohibited on Forge?

### ISSUE THREAD

**Issue by alxcool** [Stormwind99/Pantography#1]
If I understand well your mod include a way to merge maps for minecraft 1.12.2?
There is an older mod who offer the same property and also include a few more tweaks. I use it and it work fine.

https://minecraft.curseforge.com/projects/giacomos-map-merging

So either disable your mod as it could be seen as a not moral copy, or at least include a single new feature!

**Comment by Stormwind99** [comment]
My Pantography mod was created before Giacomo's Map Merging mod.

Pantography created date on Curseforge: Jan 23, 2017
Giacomo's Map Merging created date on Curseforge: Nov 13, 2017 (almost 11 months later)

Pantography also supports merging different scale maps and maps centered differently.   Pantography is also open source and available here on Github.

Also, Curseforge doesn't appear to have any rules like you mentioned that I can find: https://minecraft.curseforge.com/

**Comment by alxcool** [comment]
My mistake I apologize!, I tough pantograpy was created in jan 2018, and yeah I should read rules on curse before writing such thing.

**Comment by Stormwind99** [comment]
No prob!  Good to see someone looking out for mod authors.
